spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${NAME}
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

springdoc:
  swagger-ui:
    enabled: false
