spring:
  profiles:
    active: dev

server:
  shutdown: graceful
  compression:
    enabled: true

springdoc:
  swagger-ui:
    path: /api-docs

findex:
  openapi:
    base-url: https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService
    service-key: 14c85a4e5f8875f69d296cf68a6cd1fc911735d9b619266b79b818a9bd2c12dd